'use client';
import {useState} from 'react';
import {areas,regions} from '../data';
import countyShapes from './map-shapes.json';
const groups=[{slug:'los-angeles-county',counties:['037'],x:103,y:175},{slug:'inland-empire',counties:['065','071'],x:279,y:168},{slug:'san-diego-county',counties:['073'],x:205,y:322}];
const shapes=groups.map(g=>{const counties=countyShapes.filter(c=>g.counties.includes(c.county));const minX=Math.min(...counties.map(c=>c.bounds[0])),minY=Math.min(...counties.map(c=>c.bounds[1])),maxX=Math.max(...counties.map(c=>c.bounds[2])),maxY=Math.max(...counties.map(c=>c.bounds[3]));const scale=Math.min(1.8,410/(maxX-minX),360/(maxY-minY));return {...g,d:counties.map(c=>c.d).join(''),view:`translate(${260-(minX+maxX)/2*scale}px, ${230-(minY+maxY)/2*scale}px) scale(${scale})`};});
export default function ServiceMap(){const [selected,setSelected]=useState(null);const area=regions.find(r=>r.slug===selected);return <section className="areas section" id="service-areas"><div data-reveal><p className="eyebrow">Our part of California</p><h2>Local work.<br/>Wide reach.</h2><p>Serving Los Angeles County, San Diego County and the Inland Empire.</p><div className="region-controls">{regions.map((r,i)=><button key={r.slug} aria-pressed={selected===r.slug} onClick={()=>setSelected(selected===r.slug?null:r.slug)}><small>0{i+1}</small>{r.name}<span aria-hidden="true">+</span></button>)}</div><div className="region-info" aria-live="polite">{area?<><h3>{area.name}</h3><p>{area.intro}</p><div className="city-links">{areas.filter(a=>area.cities.includes(a.slug)).map(a=><a key={a.slug} href={`/service-areas/${a.slug}`}>{a.name}</a>)}</div><a className="text-link" href={`/service-areas/${area.slug}`}>Explore {area.name}</a></>:<p className="map-instruction">Select a region to explore local services.</p>}</div></div><div className="map-wrap" data-reveal><svg viewBox="0 0 520 490" role="group" aria-label="Interactive Southern California service region map"><defs><pattern id="map-grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="currentColor" strokeWidth=".3" opacity=".3"/></pattern></defs><rect width="520" height="490" fill="url(#map-grid)"/><g className="map-regions" style={{transform:selected?shapes.find(s=>s.slug===selected).view:'none'}}>{shapes.map(s=><g key={s.slug}><path d={s.d} tabIndex="0" role="button" aria-label={`Explore ${regions.find(r=>r.slug===s.slug).name}`} aria-pressed={selected===s.slug} className={selected===s.slug?'selected':''} onClick={()=>setSelected(selected===s.slug?null:s.slug)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(selected===s.slug?null:s.slug);}}}/><text x={s.x} y={s.y} textAnchor="middle" pointerEvents="none">{s.slug==='inland-empire'?'INLAND EMPIRE':s.slug==='san-diego-county'?'SAN DIEGO':'LOS ANGELES'}</text><circle cx={s.x} cy={s.y+14} r="2" fill="currentColor" pointerEvents="none"/></g>)}<path d={countyShapes.find(c=>c.county==="059").d} className="context-region"/><text x="135" y="230" className="map-context" textAnchor="middle">ORANGE</text></g><text x="78" y="350" className="ocean">PACIFIC</text><text x="78" y="369" className="ocean">OCEAN</text><path d="M468 425V380M468 380L463 391M468 380L473 391" stroke="currentColor" fill="none"/><text x="468" y="365" textAnchor="middle">N</text></svg>{selected&&<button className="map-reset" onClick={()=>setSelected(null)}>View all regions</button>}<small className="map-caption">Southern California · U.S. Census county boundaries</small></div></section>;}


