'use client';
import {useState} from 'react';
const projects=[
 {name:'Hillside residence',before:'featured-before',after:'featured-after',beforeSize:[1536,1152],afterSize:[864,1536],beforeAlt:'Original yellow stucco exterior of a hillside home',afterAlt:'Same hillside home with a neutral stucco finish during project completion',caption:'Exterior re-stucco'},
 {name:'Residential exterior',before:'project-6',after:'project-7',beforeSize:[853,643],afterSize:[891,628],beforeAlt:'Older single story home exterior before stucco finishing',afterAlt:'Same single story home with clean white stucco finish',caption:'A fresh exterior finish'},
 {name:'New construction',before:'project-10',after:'project-11',beforeSize:[828,431],afterSize:[719,444],beforeAlt:'Two story house with exposed wall sheathing before plaster installation',afterAlt:'Same two story house with applied stucco and detailed entry surrounds',caption:'From preparation to plaster'}
];
export default function ProjectComparison(){const [selected,setSelected]=useState(0),[after,setAfter]=useState(false);const project=projects[selected];return <figure className="featured-project" data-reveal><div className="project-selector" aria-label="Choose a transformation project">{projects.map((p,i)=><button key={p.name} aria-pressed={selected===i} onClick={()=>{setSelected(i);setAfter(false);}}>{p.name}</button>)}</div><div className="comparison" aria-label={`${project.name} before and after photographs`}><img key={project.before} src={`/projects/${project.before}.webp`} srcSet={`/projects/${project.before}-small.webp 640w, /projects/${project.before}.webp ${project.beforeSize[0]}w`} sizes="(max-width:767px) calc(100vw - 48px), 55vw" width={project.beforeSize[0]} height={project.beforeSize[1]} alt={project.beforeAlt} loading="lazy" className={after?'inactive':'active'}/><img key={project.after} src={`/projects/${project.after}.webp`} srcSet={`/projects/${project.after}-small.webp 640w, /projects/${project.after}.webp ${project.afterSize[0]}w`} sizes="(max-width:767px) calc(100vw - 48px), 55vw" width={project.afterSize[0]} height={project.afterSize[1]} alt={project.afterAlt} loading="lazy" className={after?'active':'inactive'}/><div className="compare-controls" aria-label="Choose project view"><button aria-pressed={!after} onClick={()=>setAfter(false)}>Before</button><button aria-pressed={after} onClick={()=>setAfter(true)}>After</button></div></div><figcaption><span>01 / {project.caption}</span><small>{after?'After':'Before'} · {project.name}</small></figcaption></figure>;}


