'use client';
import {useState} from 'react';
const projects=[
 {name:'Hillside residence',before:'featured-after',after:'featured-before',beforeSize:[864,1536],afterSize:[1536,1152],beforeAlt:'White hillside exterior before the yellow finish',afterAlt:'Completed yellow stucco exterior of the same hillside home',caption:'Exterior re-stucco'},
 {name:'Residential exterior',before:'project-6',after:'project-7',beforeSize:[853,643],afterSize:[891,628],beforeAlt:'Older single story home exterior before stucco finishing',afterAlt:'Same single story home with clean white stucco finish',caption:'A fresh exterior finish'},
 {name:'New construction',before:'project-10',after:'project-11',beforeSize:[828,431],afterSize:[719,444],beforeAlt:'Two story house with exposed wall sheathing before plaster installation',afterAlt:'Same two story house with applied stucco and detailed entry surrounds',caption:'From preparation to plaster'}
];
export default function ProjectComparison(){const [selected,setSelected]=useState(0),[after,setAfter]=useState(true);const project=projects[selected];return <figure className="featured-project" data-reveal><div className="project-selector" aria-label="Choose a transformation project">{projects.map((p,i)=><button key={p.name} aria-pressed={selected===i} onClick={()=>{setSelected(i);setAfter(true);}}>{p.name}</button>)}</div><div className="comparison photo-fit" style={{'--photo-ratio':(after?project.afterSize:project.beforeSize)[0]/(after?project.afterSize:project.beforeSize)[1]}} aria-label={project.name+' before and after photographs'}><img key={(after?project.after:project.before)} src={'/projects/'+(after?project.after:project.before)+'.webp'} width={(after?project.afterSize:project.beforeSize)[0]} height={(after?project.afterSize:project.beforeSize)[1]} alt={after?project.afterAlt:project.beforeAlt} loading="lazy"/><div className="compare-controls" aria-label="Choose project view"><button aria-pressed={!after} onClick={()=>setAfter(false)}>Before</button><button aria-pressed={after} onClick={()=>setAfter(true)}>After</button></div></div><figcaption><span>01 / {project.caption}</span><small>{after?'After':'Before'} · {project.name}</small></figcaption></figure>;}


