'use client';
import {useEffect,useRef,useState} from 'react';
import {services,regions,phones} from '../data';

function Dropdown({label,items,prefix}){return <details className="nav-dropdown"><summary>{label}<span aria-hidden="true">⌄</span></summary><div className="dropdown-panel">{items.map(item=><a key={item.slug} href={`${prefix}/${item.slug}`}>{item.name}</a>)}</div></details>;}
export function Header(){
 const [open,setOpen]=useState(false); const toggle=useRef(null); const panel=useRef(null);
 useEffect(()=>{if(!open)return; const old=document.body.style.overflow;document.body.style.overflow='hidden'; const key=e=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus();}if(e.key==='Tab'){const nodes=[toggle.current,...panel.current.querySelectorAll('a,summary')].filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',key);};},[open]);
 useEffect(()=>{const close=e=>{if(e.key==='Escape')document.querySelectorAll('.nav-dropdown[open]').forEach(d=>d.removeAttribute('open'));};const outside=e=>document.querySelectorAll('.nav-dropdown[open]').forEach(d=>{if(!d.contains(e.target))d.removeAttribute('open');});window.addEventListener('keydown',close);document.addEventListener('pointerdown',outside);return()=>{window.removeEventListener('keydown',close);document.removeEventListener('pointerdown',outside);};},[]);
 return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><a className="brand" href="/" aria-label="Imperial Crown home"><img src="/brand/logo-360.webp" width="360" height="155" alt="Imperial Crown Lath & Plastering"/></a><nav className="desktop-nav" aria-label="Main navigation"><Dropdown label="Services" items={services} prefix="/services"/><a href="/our-work">Our Work</a><Dropdown label="Service Areas" items={regions} prefix="/service-areas"/><a href="/about">About</a><a href="/contact">Contact</a></nav><a href="/contact" className="header-estimate">Request an estimate</a><button ref={toggle} className={`menu-toggle ${open?'is-open':''}`} aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>setOpen(!open)}><span/><span/></button></header><nav ref={panel} id="mobile-navigation" className="mobile-navigation" aria-label="Mobile navigation" hidden={!open}><Dropdown label="Services" items={services} prefix="/services"/><Dropdown label="Service Areas" items={regions} prefix="/service-areas"/><a href="/our-work">Our Work</a><a href="/about">About</a><a href="/contact">Contact</a><a className="button" href="/contact">Request an estimate</a><div className="mobile-phones">{phones.map(p=><a key={p.name} href={p.href}><small>{p.name}</small>{p.display}</a>)}</div></nav></>;
}
export function Instagram(){return <a href="https://www.instagram.com/imperial_clp/" aria-label="@imperial_clp on Instagram" target="_blank" rel="noopener noreferrer" className="instagram"><svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".75" fill="currentColor" stroke="none"/></svg><span>@imperial_clp</span></a>;}
export function Footer(){return <footer className="site-footer"><div className="footer-top"><div><a href="/" className="footer-brand">IMPERIAL CROWN<span>LATH & PLASTERING</span></a><p>Built beneath the surface.<br/>Finished to be seen.</p><small>CA License #1161215</small></div><div><p className="eyebrow">Explore</p><a href="/services">Services</a><a href="/our-work">Our Work</a><a href="/about">About</a><a href="/contact">Request an estimate</a></div><div><p className="eyebrow">Southern California</p>{regions.map(r=><a key={r.slug} href={`/service-areas/${r.slug}`}>{r.name}</a>)}<a href="/service-areas">All service areas</a></div><div><p className="eyebrow">Talk with us</p>{phones.map(p=><a key={p.name} href={p.href}>{p.name} · {p.display}</a>)}<Instagram/></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Imperial Crown Lath & Plastering</span><a href="/privacy">Privacy</a><span>20+ years. Every layer matters.</span></div></footer>;}
export function SiteEffects(){const [show,setShow]=useState(false);useEffect(()=>{const motion=matchMedia('(prefers-reduced-motion: reduce)');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));const scroll=()=>{const hero=document.getElementById('cinematic');setShow(window.scrollY>(hero?hero.offsetHeight-100:500));};scroll();window.addEventListener('scroll',scroll,{passive:true});const cursor=document.querySelector('.cursor-dot');const move=e=>{if(!motion.matches&&e.pointerType==='mouse'&&matchMedia('(pointer:fine)').matches){cursor.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;cursor.style.opacity='1';cursor.classList.toggle('interactive',Boolean(e.target.closest('a,button,summary')));}};const leave=()=>cursor.style.opacity='0';window.addEventListener('pointermove',move,{passive:true});document.addEventListener('mouseleave',leave);return()=>{observer.disconnect();window.removeEventListener('scroll',scroll);window.removeEventListener('pointermove',move);document.removeEventListener('mouseleave',leave);};},[]);return <><div className="cursor-dot" aria-hidden="true"/><a className={`mobile-cta ${show?'shown':''}`} href="/contact" tabIndex={show?0:-1}>Request an estimate</a></>;}


