export const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.socalplastering.com';
export const phones = [{name:'Diego',display:'(951) 880-3103',href:'tel:+19518803103'},{name:'Isaiah',display:'(951) 425-0490',href:'tel:+19514250490'}];
export const services = [
{slug:'stucco',name:'Stucco & re-stucco',short:'A new exterior. A solid foundation.',intro:'New stucco systems and re-stucco work for homes, additions and commercial exteriors. We work through the substrate, details and finish so the whole wall comes together.',detail:'Re-stucco starts with the condition of the existing surface. Loose material, cracks and transitions need attention before a new finish goes on. We review the wall and discuss the preparation, texture and color that fit your project.',steps:['Review the existing substrate and scope','Prepare openings, transitions and wall surfaces','Apply the specified coats and finish'],image:'project-11'},
{slug:'stucco-repair',name:'Stucco repair',short:'Repair the problem. Respect the finish.',intro:'Cracks, damaged areas and patches deserve more than a coat of paint. We assess the affected surface and plan a repair that fits the surrounding wall.',detail:'A good patch considers depth, adhesion and texture. Where damage suggests an underlying moisture issue, the cause needs to be addressed before the finish is restored. Color and texture matching are discussed up front; weathered surfaces may benefit from refinishing a larger area.',steps:['Inspect the damaged area','Remove unsound material and prepare the repair','Blend texture and review finish options'],image:'project-6'},
{slug:'lath',name:'Lath & preparation',short:'The part you don’t see matters.',intro:'The backing behind a plaster exterior carries a lot of responsibility. We handle lath and preparation with close attention to openings, edges and transitions.',detail:'A wall assembly depends on the specified weather-resistant barrier, flashing, lath attachment and accessories working together. We coordinate the scope with the builder and project requirements before material is covered.',steps:['Confirm the assembly and project requirements','Detail the barrier, flashing and openings','Install lath and accessories for the plaster coats'],image:'project-10'},
{slug:'plastering',name:'Plastering',short:'An even surface, worked by hand.',intro:'Plaster application for new work, remodels and repairs. Each coat is worked with care, from the backing to the surface people see.',detail:'The right preparation and application make a difference at corners, returns and large wall planes. We discuss the intended finish, project conditions and scope before starting so the result works with the architecture.',steps:['Review backing and surface requirements','Apply the specified plaster system','Finish edges, returns and transitions'],image:'project-8'},
{slug:'exterior-finishes',name:'Exterior finishes',short:'Texture that belongs to the architecture.',intro:'Fine textures, traditional finishes and custom exterior details. We help homeowners and builders choose a surface that suits the property.',detail:'Texture changes the way light falls across an exterior. We review the finish direction, color and existing surfaces together, including how new work will meet stone, trim and adjacent walls.',steps:['Discuss texture and color direction','Review finish samples where appropriate','Work the surface and architectural details'],image:'project-3'},
{slug:'additions-remodels',name:'Additions & remodels',short:'New work. A considered connection.',intro:'Stucco and plaster scopes for additions and remodels, with attention to the places where new construction meets the existing property.',detail:'An addition needs more than a similar color. Wall thickness, finish texture, opening details and the transition between old and new all affect the result. We coordinate those details with the project team.',steps:['Review plans and existing conditions','Coordinate preparation and connections','Finish new surfaces and blend adjoining areas'],image:'project-10'}
];
export const areas = [
{slug:'los-angeles-county',name:'Los Angeles County',region:'los-angeles-county',intro:'Stucco, plaster and lath for Los Angeles County homes, remodels and commercial properties.',detail:'Los Angeles County brings together older plaster exteriors, hillside houses and new infill construction. Matching an existing finish and coordinating access can matter as much as the final color. We review the wall condition, staging space and project scope with you before work begins.',cities:['los-angeles','pasadena','long-beach']},
{slug:'san-diego-county',name:'San Diego County',region:'san-diego-county',intro:'Exterior plaster work from coastal neighborhoods to inland San Diego communities.',detail:'San Diego County exteriors face a range of conditions, from coastal moisture to inland sun. At windows, patios and wall transitions, sound preparation gives the finish a better starting point. Tell us about your location and the existing surface so we can discuss the appropriate scope.',cities:['san-diego','carlsbad','escondido']},
{slug:'inland-empire',name:'Inland Empire',region:'inland-empire',intro:'Lath, stucco and plaster work across Riverside and San Bernardino communities.',detail:'Inland Empire projects range from established homes to new additions and larger residential builds. Strong sun, broad wall planes and changing temperatures make substrate condition and finish selection worth discussing early. Imperial Crown works with homeowners and builders on repairs, new systems and exterior updates.',cities:['riverside','temecula','rancho-cucamonga']},
{slug:'los-angeles',name:'Los Angeles',region:'los-angeles-county',intro:'Stucco repair, re-stucco and exterior plaster for Los Angeles properties.',detail:'From older Spanish-style homes to contemporary infill, Los Angeles has very different exterior details from one block to the next. We consider original texture, window returns and connections to new additions when planning the work. Share photos of the surface and information about access when requesting your estimate.'},
{slug:'pasadena',name:'Pasadena',region:'los-angeles-county',intro:'Considered plaster and stucco work for Pasadena homes and remodels.',detail:'Pasadena’s older neighborhoods include textured plaster walls, deep window returns and distinctive architectural trim. Repairs should respect those details. For a property subject to historic review, confirm any finish or color requirements with the city before finalizing the scope; we can discuss the application work around that direction.'},
{slug:'long-beach',name:'Long Beach',region:'los-angeles-county',intro:'Stucco, lath and exterior repairs for Long Beach properties.',detail:'Long Beach combines coastal homes, compact lots and established multifamily buildings. Exterior work often needs thoughtful staging and careful transitions around balconies, windows and adjoining walls. We review access and the existing finish with you so the repair or re-stucco scope is clear.'},
{slug:'san-diego',name:'San Diego',region:'san-diego-county',intro:'Exterior finishing and stucco repair for San Diego homes, additions and remodels.',detail:'San Diego’s coastal neighborhoods and inland communities call for a close look at the existing wall assembly. We pay attention to openings, exposed edges and the surfaces around outdoor living areas. A repair estimate starts with the damage itself and a conversation about how the finished area should meet the rest of the exterior.'},
{slug:'carlsbad',name:'Carlsbad',region:'san-diego-county',intro:'Stucco and plaster work for Carlsbad exterior updates and repairs.',detail:'Carlsbad properties range from coastal houses to inland planned neighborhoods. Before selecting a new texture or color, check any applicable association requirements. We discuss wall preparation, transitions to stone or trim and the finish direction so exterior updates feel consistent across the property.'},
{slug:'escondido',name:'Escondido',region:'san-diego-county',intro:'Plaster, lath and stucco services for Escondido properties.',detail:'Escondido’s inland setting includes ranch-style homes, hillside sites and newer residential construction. Broad sunlit walls make uneven textures and patches easy to notice. We review the condition of the substrate and discuss whether a localized repair or a larger finish area makes sense.'},
{slug:'riverside',name:'Riverside',region:'inland-empire',intro:'Stucco, re-stucco and lath work for Riverside homes and building projects.',detail:'Riverside includes older homes near the city center and newer properties with large exterior wall planes. Repairs, additions and finish updates each call for a different scope. We look at texture continuity, opening details and the connection between new work and the existing exterior.'},
{slug:'temecula',name:'Temecula',region:'inland-empire',intro:'Exterior plaster and stucco for Temecula homes, remodels and outdoor spaces.',detail:'Temecula projects often bring together stucco walls, stone accents and covered outdoor living areas. Those material connections deserve attention before the final coat. We discuss access, finish direction and any neighborhood requirements with you while reviewing the work.'},
{slug:'rancho-cucamonga',name:'Rancho Cucamonga',region:'inland-empire',intro:'Stucco repairs, lath and exterior finishes in Rancho Cucamonga.',detail:'Foothill properties and established neighborhoods in Rancho Cucamonga include exposed wall faces, tall entries and detailed trim. We review staging needs and the condition around openings before starting. For repairs, the aim is to prepare the affected area properly and make a considered connection to the surrounding texture.'},
{slug:'riverside-county',name:'Riverside County',region:'inland-empire',intro:'Exterior stucco and plaster work throughout Riverside County.',detail:'From western Riverside County neighborhoods to larger inland properties, project access and existing wall condition vary. We review new construction, repairs and remodel scopes directly with the homeowner or builder.',cities:['riverside','temecula']},
{slug:'san-bernardino-county',name:'San Bernardino County',region:'inland-empire',intro:'Lath, plaster and stucco work for San Bernardino County projects.',detail:'San Bernardino County includes foothill neighborhoods, established city homes and expanding residential developments. Preparation, access and matching existing textures shape each scope. Contact us with your project location to discuss availability.',cities:['rancho-cucamonga']},
{slug:'orange-county',name:'Orange County',region:'los-angeles-county',intro:'Discuss your Orange County stucco or plaster project with Imperial Crown.',detail:'Our existing service coverage includes Orange County inquiries. Coastal exteriors, association requirements and existing finish conditions vary by property. Contact Diego or Isaiah to confirm availability and talk through your location and scope.'}
];
export const regions = areas.slice(0,3);
export function pageMeta(title,description,path){return {title,description,alternates:{canonical:path},openGraph:{title:`${title} | Imperial Crown`,description,url:path,images:[{url:'/projects/project-11.webp',width:719,height:444}]},twitter:{card:'summary_large_image',title,description,images:['/projects/project-11.webp']}};}

